{% set version = "1.4.2" %}

package:
  name: snuggs
  version: {{ version }}

source:
  fn: snuggs-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/snuggs/snuggs-{{ version }}.tar.gz
  sha256: 8d56182fc83e1a1893284f69abd35751ce30e8f0a33794c2802e7e5d6547e1f1

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - click
    - numpy
    - pyparsing

test:
  imports:
    - snuggs

about:
  home: https://github.com/mapbox/snuggs
  license: MIT
  summary: 'Snuggs are s-expressions for NumPy.'
  description: |
    Snuggs makes simple calculator programs possible.
  doc_url: https://pypi.python.org/pypi/snuggs
  doc_source_url: https://github.com/mapbox/snuggs
  dev_url: https://github.com/mapbox/snuggs

extra:
  recipe-maintainers:
    - ocefpaf
