{% set version = "1.4.5" %}

package:
  name: snuggs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/snuggs/snuggs-{{ version }}.tar.gz
  sha256: a315f8fc2d781225ffee92081c7e20217ba178e9b192ffd26b85a0013c056d2c

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - pyparsing

test:
  imports:
    - snuggs

about:
  home: https://github.com/mapbox/snuggs
  license: MIT
  license_file: LICENSE
  summary: 'Snuggs are s-expressions for NumPy'

extra:
  recipe-maintainers:
    - ocefpaf
