{% set version = "1.4.4" %}

package:
  name: snuggs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/snuggs/snuggs-{{ version }}.tar.gz
  sha256: 57b1a3f2702d76d901c8262f5b6c8eac49c5636a64c6d88f343d87f17ec2c6b5

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - pyparsing

test:
  imports:
    - snuggs

about:
  home: https://github.com/mapbox/snuggs
  license: MIT
  license_file: LICENSE
  summary: 'Snuggs are s-expressions for NumPy'

extra:
  recipe-maintainers:
    - ocefpaf
