{% set version = "1.4.1" %}

package:
  name: snuggs
  version: {{ version }}

source:
  fn: snuggs-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/snuggs/snuggs-{{ version }}.tar.gz
  sha256: e1d3c9364cec1b1b938627ebfc74f040be66711072d3ae754d844b9435f4940c

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - click
    - numpy
    - pyparsing

test:
  imports:
    - snuggs

about:
  home: https://github.com/mapbox/snuggs
  license: MIT
  summary: 'Snuggs are s-expressions for NumPy.'

extra:
  recipe-maintainers:
    - ocefpaf
