{% set version = "1.4.0" %}

package:
    name: snuggs
    version: {{ version }}

source:
    fn: snuggs-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/s/snuggs/snuggs-{{ version }}.tar.gz
    md5: 2b40406f63e9564904a96bd6faba23ea

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - click
        - numpy
        - pyparsing

test:
    imports:
        - snuggs

about:
    home: https://github.com/mapbox/snuggs
    license: MIT
    summary: 'Snuggs are s-expressions for NumPy.'

extra:
    recipe-maintainers:
        - ocefpaf
