{% set version = "1.4.3" %}

package:
  name: snuggs
  version: {{ version }}

source:
  fn: snuggs-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/snuggs/snuggs-{{ version }}.tar.gz
  sha256: d819e52a6b104936b293b625e5ab53cb8b95194643525a7d181334d743a77625

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - click
    - numpy
    - pyparsing

test:
  imports:
    - snuggs

about:
  home: https://github.com/mapbox/snuggs
  license: MIT
  summary: 'Snuggs are s-expressions for NumPy.'

extra:
  recipe-maintainers:
    - ocefpaf
