{% set version = "1.4.3" %}

package:
  name: snuggs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/snuggs/snuggs-{{ version }}.tar.gz
  sha256: d819e52a6b104936b293b625e5ab53cb8b95194643525a7d181334d743a77625

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - pyparsing

test:
  imports:
    - snuggs

about:
  home: https://github.com/mapbox/snuggs
  license: MIT
  license_file: LICENSE
  summary: 'Snuggs are s-expressions for NumPy'

extra:
  recipe-maintainers:
    - ocefpaf
