travis:
  secure:
    BINSTAR_TOKEN: mO65GurLcWwVcqTVznBUCQZY/IRVV9aLjkXA8q294dQbkBBzPZW59aQosr0orYY/Yp2LykX0A6ptV343z5XXhs596155AzW04Ho+oFNoGS1m3fdrvnt4qFA+bRsOHF3MItqzBN+Jd5hLEd6WHcz2rlyY2wq/842d6Mla30oGxG1gs5nJ8tf43M/Nfd5zsvNM9SQ+J0SmK9TYP3+AS7akF0nqvdcfVdBrpvybgHNRRuTaobE5mc4kRVuveZYlO82PVcQcjFBOxJgtbmdt8UbTQLKjxtstq5u2bXoR2koGk4UBNe4pHdh1/4ykwZYW40ez7B9Cs7zkppyPWveIj5fa/ad2gSCaM6m/Yk5bycV77li27vwhnmCzIkZkervpzj45JHhPck5K1KRGhk3Z0JwXULxT5MSTLACZm5wZOO2cZ8Fmp+qFVOXL2tvWvOxLK9gYOJCYgMomr8ZWw+bGrfQohVtyKlc1bQpRimBwbtCqOZAez3tjwvw2HSqfGquKEj0eGqGuiSIN6VO3ELasGECdl7LebfIVSqTE5tsAKXrHAES0fslUUcKN8fVAXjd/rHSlM/zDBqbXyEq+7j/pMfL1kRY+jALYhAjzaHtvYrANddr0axht9bd4c7DyUEj0ocnkTkiqmgaSbskmVyqkSxICgKKmWFbOnSg4eqqIDOOP9hc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
