travis:
  secure:
    BINSTAR_TOKEN: BNCoYBSWqeJF3bpRFrNwgWT6rtaQ+gUDpfgUXCHHCeB5np77g1fhQGDFgBHHgj/Bdcc0u7Ci5EKfKGKb3mVC9/5NB696AG8paVmIdqkOzTDhKfk38KOt6t/WVBPKkg4fHwaqmlqsnYg/iMZXI0kV/GhBbJAZ8K2MKrETZzCUcuESj+gmq87uE6w/ynhDm3ry25oRyeswWihx14S5khOroeqH8BKJ/rI5OCkn2evVB0TFtoXtesVZ/7NgYZBMlXpcaE4cNyuaSPMF+lfvnwOb8D3ZJbkKx7oyPlmUk8KMaWDfEfQ4jS15Jy5CBAUKbXH10t6dKzWjjKC3BUY4/PYGtSvSc1zHLUhShfmh0hxvKcN5Pq/0lV2b4HOkPhahDZxPLZr2YN1ul95VxKLB+beEdhQn8fEo4MUddm1KWyR2qNLfc8c6h3xp7GVw99zsAgq/sbOxdDhOtuRNAwmm9r2OJrlTXIugX7zoX3IXBOyxLIBUcwCo9qdwbTC5SRfk+kdoqeS/VaR0OscGfTMFD/MrBhz5Jyzhy33uuz5m/CRAhQCkx80sULZgUHrOlilynJNVB9crW4lfbqqg9KWNDWW6hq9fJmLP8fLXNTrnLRwiQXDtZAPAmH7Wx0/Rc8VOuYtviYLQK3yJtDHevzpZH2tyZmKTbdeDOajjAjd8TnaBPc8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
